version: "3"

services:
  elk1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elk-data:/var/lib/elasticsearch
      - ./elasticsearch.yml:/var/lib/elasticsearch/config/elasticsearch.yml
    networks:
      - elk-network

  full-indexer-service:
     container_name: full-indexer-service-container
     image: full-indexer-service
     build:
       context: ./
       dockerfile: Dockerfile
     ports:
      - 8080:8080
     environment:
       ELK_IP: elk1:9300
       ELK_IP1: http://elk1:9200
      CLUSTER_NAME: docker-cluster
     depends_on:
      - elk1
     networks:
      - elk-network

volumes:
  elk-data:

networks:
  elk-network:
    driver: bridge